### ISSUE TITLE
Add Modern Algorithm Design - MAD 

### ISSUE THREAD

**Issue by Viddesh1** [tusuii/All-Pracs#17]
Hi @tusuii ,

I want to add a subject naming MAD codes in your codebase. 

Could you create a new branch naming "MAD" in your own remote github repository? Since, I don't have any write access for branch creation rules.

 So, That I can send a pull request directly for "MAD" branch present in your remote repository from my remote branch naming "MAD" that I would folk from your repository once new branch is created in your remote github repository of the branches.

Kindly acknowledge when new branch is created from your end naming "MAD".

Thanks!
Viddesh

**Comment by tusuii** [comment]
Sure @Viddesh1 👍

**Comment by Viddesh1** [comment]
Thanks for creating a new branch.
I have to create one more commit for the README.MD file present in the main branch with 'proper subject name' and 'branch name url'

**Comment by tusuii** [comment]
Heyy @Viddesh1 ,
You can do one more thing, if you can add branch link to main repo readme as a quick link with some information, that will be great. 

Regards 
@tusuii
